# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64\x64ressbook.proto\"%\n\x04\x63\x61rd\x12\r\n\x05\x63olor\x18\x01 \x02(\t\x12\x0e\n\x06number\x18\x02 \x02(\x05')



_CARD = DESCRIPTOR.message_types_by_name['card']
card = _reflection.GeneratedProtocolMessageType('card', (_message.Message,), {
  'DESCRIPTOR' : _CARD,
  '__module__' : 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:card)
  })
_sym_db.RegisterMessage(card)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARD._serialized_start=21
  _CARD._serialized_end=58
# @@protoc_insertion_point(module_scope)
